### ISSUE TITLE
Update `marked` and `marked-terminal`

### ISSUE THREAD

**Issue by targos** [adonisjs/sink#32]
Versions 4 of `marked` and 5 of `marked-terminal` are available.
They are native ESM packages now, but since they are used in async functions, we could dynamically `import()` them.

**Comment by RomainLanz** [comment]
But to do that, do we have to migrate the entire package to ESM?

**Comment by targos** [comment]
Not if we use dynamic import

**Comment by targos** [comment]
Actually, I'm not sure we can, because AFAIK there's still no way with TypeScript to prevent transpilation of `import('')` to `Promise.resolve().then(() => require(''))`

**Comment by targos** [comment]
Maybe `await eval('import("")')` 😄

**Comment by targos** [comment]
From https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1073145723, it seems we can have it work by using `.cts` extension. I'll give it a try.

**Comment by thetutlage** [comment]
It will be a dream to have ESM dependencies work. I am not able to update a lot of packages right now

**Comment by thetutlage** [comment]
I got it work with https://github.com/davidmarkclements/inclusion. let's see if the tests pass on both windows and linux

**Comment by thetutlage** [comment]
Looks good https://github.com/adonisjs/sink/runs/6268421829?check_suite_focus=true.

@targos Do you want to check it manually once on your Windows before I publish the package?

**Comment by targos** [comment]
What can I do to test it?

**Comment by thetutlage** [comment]
Good question. I think running the tests on your local Windows won't be different from the CI.

So, lemme actually release the package

**Comment by thetutlage** [comment]
Here we go https://github.com/adonisjs/sink/releases/tag/v5.3.0
