### ISSUE TITLE
ESM

### ISSUE THREAD

**Issue by ThibaultPointurier** [adonisjs/sink#35]
## Package version
5.3.0

## Node.js and npm version
Node : 16.14.2
npm: 8.5.0

## Sample Code (to reproduce the issue)
node ace configure @adonisjs/lucid

https://media.discordapp.net/attachments/971148771859791914/971149190849790022/Screenshot_10.png

**Comment by thetutlage** [comment]
Hey! Can you please re-install all dependencies and confirm if you still have the issue or not?

```sh
rm -rf node_modules
rm package-lock.json

npm install
```

Just double check that you have `@adonisjs/sink@5.3.1` installed by running the following command.

```sh
npm ls @adonisjs/sink

└─┬ @adonisjs/assembler@5.6.2
  └── @adonisjs/sink@5.3.1
```
